// inlang/source-code/paraglide/prototyping/svelte-tree/src/App.svelte
<script lang="ts">
  import { languageTag, changeLanguageTag } from "./paraglide/runtime";
  import * as m from "./paraglide/messages"
  import ParaglideJS from "./Adapter.svelte"

  $: name = "Samuel"


</script>

<ParaglideJS>
  <p>{m.onlyText()}</p>
  <p>{m.multipleParams({ name, count: 5})}</p>
  <button on:click={() => name = "Felix"}>change name</button>
  <button on:click={async () => {
    changeLanguageTag("de");
    console.log("language tag changed");
  }}>change language tag to "de"</button>
  <p>the current language tag is {languageTag}</p>
</ParaglideJS>

// inlang/source-code/paraglide/prototyping/react/src/App.tsx
/* eslint-disable react-hooks/rules-of-hooks */
import * as m from "./paraglide/messages"
import { Paraglide, useParaglide, useParaglideState } from "./paraglide/runtime"

function App() {
	console.log("rendering app")
	return (
		<Paraglide.Provider value={useParaglideState()}>
			<>
				<Component></Component>
				<Component2></Component2>
			</>
		</Paraglide.Provider>
	)
}

function Component() {
	console.log("rendering component 1")
	const { setLanguageTag } = useParaglide()

	return (
		<>
			{/* <p>{languageTag}</p> */}
			<button
				onClick={() => {
					setLanguageTag("de")
				}}
			>
				Change language tag
			</button>
			<p>{m.loginButton()}</p>
		</>
	)
}

function Component2() {
	console.log("rendering component 2")

	return (
		<>
			<p>{m.loginButton()}</p>
		</>
	)
}

export default App
