// inlang/source-code/paraglide/prototyping/svelte/src/App.svelte
<script lang="ts">
  import { setCurrentLanguageTag } from "./paraglide/runtime";
  import { m} from "./paraglide/runtime"
</script>


<p>{$m("onlyText", {})}</p>
<p>{$m("multipleParams", { name: "Samuel", count: 5})}</p>


<button on:click={async () => {
  setCurrentLanguageTag("de");
  console.log("language tag changed");
  // console.log($m("multipleParams", { name: "Samuel", count: 5 }))
}}>change language tag to "de"</button>


<!-- <Manual></Manual> -->

// inlang/source-code/paraglide/prototyping/react-function/src/App.tsx
/* eslint-disable react-hooks/rules-of-hooks */
import { m } from "./runtime"
import { Paraglide, useParaglide, useParaglideState } from "./runtime"

function App() {
	console.log("rendering app")
	return (
		<Paraglide.Provider value={useParaglideState()}>
			<>
				<Component></Component>
				<Component2></Component2>
			</>
		</Paraglide.Provider>
	)
}

function Component() {
	console.log("rendering component 1")
	const { setLanguageTag } = useParaglide()

	return (
		<>
			{/* <p>{languageTag}</p> */}
			<button
				onClick={() => {
					setLanguageTag("de")
				}}
			>
				Change language tag
			</button>
			<p>{m("loginButton", {})}</p>
		</>
	)
}

function Component2() {
	console.log("rendering component 2")

	return (
		<>
			<p>{m("loginButton", {})}</p>
		</>
	)
}

export default App
